#!/bin/bash -l
#rvm use ruby-head >/dev/null
if [[ "$1" == "" ]] || [[ "$1" == "." ]]; then
  vim -c "cd $PWD"
else
  IFS=":" read -ra FP <<< "$1"
  if [ ${#FP[@]} == '1' ]; then
    FP[1]="0"
  fi

  vim -c "cd $PWD" +${FP[1]} "${FP[0]}"
fi
