#!/bin/bash

#for f in **/*.rb **/*.js; do sed -i -e '$a\' $f; done
FILE_LIST=$(ag --search-files --nocolor -g '.')
echo "$FILE_LIST" | xclude_packed_files | gtags -f - -O

TAGS_PATH=`global -p`
if [[ "$TAGS_PATH" == "" ]]; then
  echo "This directory doesn't have any GTAGS yet."
  exit 1;
fi

DUMP_FILE="$TAGS_PATH/tags_dump.txt"

rm -f "$DUMP_FILE"
global --result=ctags-x -e '.*' | perl -pe 's/^([^ ]+) +(\d+) +([^ ]+?) +(.+?)$/\1\t\4\t\3\t\2/g'  >> "$DUMP_FILE"
global --result=ctags-x -P | perl -pe 's/^([^ ]+) +(\d+) +([^ ]+?) +$/\3\t\1\t\3\t\2/g' >> "$DUMP_FILE"
echo "$FILE_LIST" | perl -pe 's/^(.*)$/\1\tpath\t\1\t1/g' >> "$DUMP_FILE"
sort -u -o "$DUMP_FILE" "$DUMP_FILE"
