#!/bin/bash

export conf=~/.gmailpopup_config
export checksum_file=/tmp/gmail_checksum_$(whoami)
export tmp=/tmp/gmailpopup

if [ "$1" = "--reconfigure" ]; then
 rm -f $conf $checksum_file
fi

if [ ! -f $conf ]; then 
 A=$(zenity --title="Setup" --entry --text="Enter email address:")
 [ -z $(echo ${A}) ] && exit 1
 B=$(zenity --title="Setup" --entry --text="Enter password for ${A}" --hide-text)
 [ -z $(echo ${B}) ] && exit 1
 echo $A > $conf
 echo $B | base64 >> $conf
 export newconfig=true
fi
email=$(head -1 ${conf})

curl -s -u $email:$(tail -1 ${conf} | base64 --decode) https://mail.google.com/mail/feed/atom --connect-timeout 10 --max-time 10 | grep title  > ${tmp}

if [ "${newconfig}" = "true" ]; then
 if [ ! -s ${tmp} ]; then 
  zenity --error --title "An error occurred" --text "Sorry, I got no data back from Google. 
Either the connection timed out or the password was wrong.

To reconfigure run 'gmailpopup --reconfigure'."; 
  exit 1
 fi
 for package in curl gnome-gmail; do
 IsInstalled=$(dpkg --list | grep $package -c)
  if [ "${IsInstalled}" = 0 ]; then
  zenity --warning --title "Missing package" --text \
"The ${pkg} package is missing. To install it use:

sudo apt-get install ${pkg}"
  fi
 done
fi

count=$(echo `wc -l ${tmp} | cut -d' ' -f1` -1 | bc) 

if [ "${count}" = 0 ]; then
 checksum=$(echo "nothing" | md5sum)
else 
 first_email=$(cat ${tmp} | grep -v "Inbox for ${email}" | head -1 | awk -F '\>' '{print $2}' | awk -F '\<' '{print $1}')
 checksum=$(cat ${tmp} | md5sum)
fi

if [ -f $checksum_file ]; then 
 if [ "$(echo $checksum)" == "$(cat ${checksum_file})" ]; then
  echo $checksum > $checksum_file 
  rm -f $tmp
  exit 1 
 fi
fi

echo $checksum > $checksum_file 

if [ "$count" -gt 0 ]
then
 if [ "$count" -eq 1 ]; then 
  notify-send "New email for $email" "$first_email" -i gnome-gmail
 else
  notify-send "New email for $email" "$count unread emails." -i gnome-gmail
 fi
fi
if [ "${newconfig}" = "true" ]; then
 zenity --info --title "Setup finished" --text "Setup was successful."
fi

rm -f $tmp
