#!/usr/bin/env ruby

gems = {}
Gem::Specification.each do |g|
  if gems[g.name]
    if g.version > gems[g.name].version
      gems[g.name] = g
    end
  else
    gems[g.name] = g
  end
end

to_dir = File.expand_path("~/.gems_copy/#{RUBY_ENGINE}_#{RUBY_VERSION}_#{RUBY_PLATFORM}")

puts "mkdir -p #{to_dir}"
puts "rm -rf .*"

gems.values.each do |g|
  puts "cp -R #{g.gem_dir} ."
end
