#!/bin/bash

function execute_player() {
  mpv --no-lirc --framedrop=yes --fs --alang=jpn,jp,eng,en --slang=eng,en --cache=10000 "$@" >/dev/null 2>&1
}

. /home/bloopletech/key/third_party/mpv-build/mpv/TOOLS/mpv_identify.sh ID_ "$@"

WIDTH=$ID_width
HEIGHT=$ID_height

if [[ $WIDTH -eq 1920 && $HEIGHT -eq 1080 ]]; then
  execute_player "$1"
elif [[ $WIDTH -lt 601 || $HEIGHT -lt 401 ]]; then
  NEW_WIDTH=$(expr $WIDTH \* 2)
  execute_player "--vf=scale=$NEW_WIDTH:-2,expand=1920:1080" --sws=9 "$@"
elif [[ $WIDTH -lt 1001 || $HEIGHT -lt 901 ]]; then
  NEW_WIDTH=$(expr \( $WIDTH \* 3 \) / 2)
  execute_player "--vf=scale=$NEW_WIDTH:-2,expand=1920:1080" --sws=9 "$@"
else
  execute_player "--vf=expand=1920:1080" "$1"
fi

