#!/bin/bash

ARGUMENTS="${@:1:($#-1)}" #arguments, except the video file path
VIDEO="${!#}" #video file path
VIDEO="${VIDEO/play/http}"
#VIDEO="${VIDEO/#play:\/\//}"

function execute_player_ubuntu() {
  mpv --vo=opengl-hq --fs --alang=jpn,jp,eng,en --slang=eng,en --cache=10000 "$@" $ARGUMENTS "$VIDEO" >/dev/null 2>&1
}

function execute_player_osx() {
  /Applications/mpv.app/Contents/MacOS/mpv --terminal --really-quiet "$@" $ARGUMENTS "$VIDEO" >/dev/null 2>&1 &
}

if [[ "$OSTYPE" == "linux-gnu" ]]; then
  execute_player_ubuntu
elif [[ "$OSTYPE" == "darwin"* ]]; then
  execute_player_osx
fi
