#!/bin/bash

declare -x $(cat /proc/meminfo | sed -n 's/\([A-Za-z]\+\): \+\([0-9]\+\)\( kB\)\?/MEMINFO_\1=\2/gp' | paste -s -d ' ');
dc -e "1 k $MEMINFO_SwapTotal $MEMINFO_SwapFree - 1048576 / n"
echo " GB"
