#!/bin/bash

while read FILE
do
  PRINT=1
  LINES=0
  while read -n 1001 LINE
  do
    let LINES++
    if [[ "$LINES" -gt 10000 ]]; then
      PRINT=0;
      break;
    fi
    if [[ "${#LINE}" -gt 1000 ]]; then
      PRINT=0;
      break;
    fi
  done < "$FILE"
  if [[ "$PRINT" == "1" ]]; then
    echo "$FILE";
  fi
done

