#!/bin/bash
exec >>/var/log/auto-update.log 2>&1
set -e
set -x

export PATH="/usr/local/sbin:/usr/local/bin:/usr/sbin:/usr/bin:/sbin:/bin"

echo "Starting update..."
date
apt-fast update
apt-fast -q -q upgrade
date
echo "Update finished"
